# Podfile for Flutter project "appfotajer"
platform :ios, '11.0'

# use_frameworks!  # Uncomment if any plugin requires frameworks
use_modular_headers!

target 'Runner' do
  # Flutter Pod
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  # Firebase Pods
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'

  # Other plugin Pods
  pod 'flutter_local_notifications', :path => '.symlinks/plugins/flutter_local_notifications/ios'
  pod 'flutter_background_service', :path => '.symlinks/plugins/flutter_background_service/ios'
  pod 'provider', :path => '.symlinks/plugins/provider/ios'
  pod 'flutter_bloc', :path => '.symlinks/plugins/flutter_bloc/ios'
  pod 'image_picker', :path => '.symlinks/plugins/image_picker/ios'
  pod 'flutter_image_compress', :path => '.symlinks/plugins/flutter_image_compress/ios'
  pod 'cached_network_image', :path => '.symlinks/plugins/cached_network_image/ios'
  pod 'appwrite', :path => '.symlinks/plugins/appwrite/ios'
  pod 'flutter_secure_storage', :path => '.symlinks/plugins/flutter_secure_storage/ios'
  pod 'shared_preferences', :path => '.symlinks/plugins/shared_preferences/ios'
  pod 'geolocator', :path => '.symlinks/plugins/geolocator/ios'
  pod 'google_maps_flutter', :path => '.symlinks/plugins/google_maps_flutter/ios'
  pod 'intl', :path => '.symlinks/plugins/intl/ios'
  pod 'google_fonts', :path => '.symlinks/plugins/google_fonts/ios'
  pod 'fluttertoast', :path => '.symlinks/plugins/fluttertoast/ios'
  pod 'uuid', :path => '.symlinks/plugins/uuid/ios'
  pod 'permission_handler', :path => '.symlinks/plugins/permission_handler/ios'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
