# Uncomment this line to define a global platform for your project
platform :ios, '12.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

# Use frameworks instead of static libraries
use_frameworks!
use_modular_headers!

# Ignore all warnings from all pods
inhibit_all_warnings!

target 'Runner' do
  # Flutter pods
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  # Add any additional pods here, for example:
  # pod 'Firebase/Analytics'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # Ensure Swift version compatibility
      config.build_settings['SWIFT_VERSION'] = '5.0'
    end
  end
end
