# Do not edit. This file is generated by Flutter.
# Flutter iOS Pod helper

require 'fileutils'

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. Run 'flutter pub get' first."
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT=(.*)/)
    return matches[1].strip if matches
  end

  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}"
end

# Path to Flutter podhelper.rb
flutter_tools_podhelper = File.join(flutter_root, 'packages', 'flutter_tools', 'bin', 'podhelper')

unless File.exist?(flutter_tools_podhelper)
  raise "Flutter podhelper not found at #{flutter_tools_podhelper}. Ensure your Flutter SDK is complete."
end

require File.expand_path(flutter_tools_podhelper)

# Setup function to be called from Podfile
def flutter_ios_podfile_setup
  flutter_application_path = File.expand_path('..', __FILE__)
  generated_xcconfig = File.join(flutter_application_path, 'Flutter', 'Generated.xcconfig')

  unless File.exist?(generated_xcconfig)
    raise "Generated.xcconfig not found at #{generated_xcconfig}. Run 'flutter pub get' first."
  end

  # Load Flutter iOS pod setup
  flutter_install_all_ios_pods(flutter_application_path)
end
