# Do not edit. This file is generated by Flutter.
# See: https://flutter.dev/docs/development/ios-project-migration

require 'fileutils'

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. Run flutter pub get first."
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

def flutter_ios_podfile_setup
  # Configures the Flutter iOS pod dependencies
  flutter_application_path = File.expand_path('..', __FILE__)
  load File.join(flutter_application_path, 'Flutter', 'Generated.xcconfig')
end
